### ISSUE TITLE
yolk doesn't work in python3

### ISSUE THREAD

**Issue by hemna** [myint/yolk#21]
```
 vagrant@vagrant-openSUSE-Leap  ~/cinder   master  pip install yolk                                 
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting yolk
  Downloading https://files.pythonhosted.org/packages/2b/c0/73510e50668b70f3fad25328c58d7a29a300a2e452058dfdcb7c7538af7b/yolk-0.4.3.tar.gz (86kB)
     |████████████████████████████████| 92kB 463kB/s 
Requirement already satisfied: setuptools in ./.tox/docs/lib/python3.4/site-packages (from yolk) (41.2.0)
Building wheels for collected packages: yolk
  Building wheel for yolk (setup.py) ... done
  Stored in directory: /home/vagrant/.cache/pip/wheels/70/ea/49/1364272c97de7b2d9068d5759b097a9ded59df1bddb80a5a9c
Successfully built yolk
Installing collected packages: yolk
Successfully installed yolk-0.4.3
 vagrant@vagrant-openSUSE-Leap  ~/cinder   master  yolk -V sphinx                                    Traceback (most recent call last):
  File "/home/vagrant/cinder/.tox/docs/bin/yolk", line 6, in <module>
    from yolk.cli import main
  File "/home/vagrant/cinder/.tox/docs/lib/python3.4/site-packages/yolk/cli.py", line 262
    print " %s %s (%s)" % (project_name, dist.version,
                      ^
SyntaxError: invalid syntax

**Comment by myint** [comment]
https://github.com/myint/yolk#id1
