### ISSUE TITLE
yolk -S foo raises AttributeError: 'NoneType' object has no attribute 'insert'

### ISSUE THREAD

**Issue by ioistired** [myint/yolk#22]
```
➤ yolk -S foo
Traceback (most recent call last):
  File "/home/io/.local/bin/yolk", line 10, in <module>
    sys.exit(main())
  File "/home/io/.local/share/pipx/venvs/yolk1977/lib/python3.7/site-packages/yolk/cli.py", line 1173, in main
    my_yolk.run()
  File "/home/io/.local/share/pipx/venvs/yolk1977/lib/python3.7/site-packages/yolk/cli.py", line 224, in run
    return getattr(self, action)()
  File "/home/io/.local/share/pipx/venvs/yolk1977/lib/python3.7/site-packages/yolk/cli.py", line 801, in pypi_search
    spec.insert(0, search_arg.strip())
AttributeError: 'NoneType' object has no attribute 'insert'
```

**Comment by ioistired** [comment]
Oh, that traceback is from yolk1977, not yolk3k. On yolk3k I get the same traceback though:
```
➤ pipx run --spec yolk3k yolk -S foo
Traceback (most recent call last):
  File "/home/io/.local/share/pipx/.cache/0e1ebcfb813fc5a/bin/yolk", line 10, in <module>
    sys.exit(main())
  File "/home/io/.local/share/pipx/.cache/0e1ebcfb813fc5a/lib/python3.7/site-packages/yolk/cli.py", line 1171, in main
    my_yolk.run()
  File "/home/io/.local/share/pipx/.cache/0e1ebcfb813fc5a/lib/python3.7/site-packages/yolk/cli.py", line 224, in run
    return getattr(self, action)()
  File "/home/io/.local/share/pipx/.cache/0e1ebcfb813fc5a/lib/python3.7/site-packages/yolk/cli.py", line 801, in pypi_search
    spec.insert(0, search_arg.strip())
AttributeError: 'NoneType' object has no attribute 'insert'
```
